### ISSUE TITLE
Should this include properties from other namespaces?

### ISSUE THREAD

**Issue by MetadataDeluxe** [MuseosAbiertos/Adobe-Bridge-Custom-Metadata-JSON-Presets#4]
Since we have other presets for dc, xmpRights, and photoshop, I didn't include them in this - I only included properties unique to the Iptc4xmpCore namespace. I thought this would reduce redundancy, but now I'm wondering if I it will be confusing (annoying) to people who might expect to find them all in one preset. In other words, should the IPTC Core preset include all properties in the IPTC Core spec, including dc, xmpRights, and photoshop? https://www.iptc.org/std/photometadata/specification/IPTC-PhotoMetadata#iptc-core-schema-1-2-specifications

Otherwise, I could add a note that the preset is only for the unique Iptc4xmpCore properties.

**Comment by mrtngrsbch** [comment]
That is the intention of the Readme, since JSON cannot include comments.
It is true that it can be confusing. 
I started from the idea that a 'preset' can contain 'grouped needs', rather than properties of a single namespace. That is: not only ISADG, but some IPTC or XMP tags.

Honestly, this is not a subject on which I have a fixed opinion and I am flexible to ideas and suggestions, in order to maintain the coherence of the repository.

What do you suggest? How do you think it is best to document ?

**Comment by MetadataDeluxe** [comment]
Yes, 'grouped needs' makes sense and is in the spirit of modern data modeling. I will propose edits to the README to explain the Iptc4xmpCore preset.

**Comment by mrtngrsbch** [comment]
Perfect. With that idea we can have many 'presets'; with 'grouped needs' and others with a single 'namespace'. 

It's my intention, during the year, to create a specific preset for Museums in Buenos Aires, Argentina. This case would be a preset based on ISAD(G), but also containing VRA, DC & IPTC.

**Comment by mrtngrsbch** [comment]
Hi @MetadataDeluxe ,
I just included a description for [core_properties_view.json] using your text... Please feel free to modify it if necessary.

**Comment by MetadataDeluxe** [comment]
@mrtngrsbch that looks great. It will be good for people who want to use a few of the most commonly used properties. They can just remove the properties they don't need.
