### ISSUE TITLE
'vrae_properties_view.json' Vs. 'VRA Bridge Metadata Tools'

### ISSUE THREAD

**Issue by mrtngrsbch** [MuseosAbiertos/Adobe-Bridge-Custom-Metadata-JSON-Presets#8]
Hi @MetadataDeluxe,

A few weeks ago I found '[VRA Bridge Metadata Tools](http://metadatadeluxe.pbworks.com/w/page/108523528/VRA%20Bridge%20Metadata%20Tools)' and I find the integration with the Getty vocabularies excellent. Nice work!

But, we also have the json script for Custom Panels.

Questions:
- How do both tools coexist ?
- Why make a simplified version if there is already a panel?
- What is the future of both?

best

**Comment by MetadataDeluxe** [comment]
Hi @mrtngrsbch,

There is no formal connection between the Custom Panels and the VRA Bridge Metadata Tools, they are independently developed and maintained. 

The VRA Tools were first created in 2014 and only used the simple display properties. I wanted to keep it simple for users to enter data and simple to code. Later, I added the structured properties and integrated the Getty vocabulary linked data function to make it easier to grab controlled vocabulary terms. I added the VRA json script for Custom Panels for users who do not need the full complexity of the VRA Bridge Metadata Tools and prefer the simple metadata side panel UI. I used to have a simple VRA side panel, but bugs in the current Bridge XML panel environment prevent it from working. When the Custom Panels were recently released, it seemed like an opportunity to bring back the simplified VRA panel.

I am not certain about the future of the VRA Bridge Metadata Tools because I'm not sure how many people are using them and Bridge updates continually introduce bugs that break them. For example, the VRA Tool Getty vocabulary search will not work in Bridge 2021 (I have identified the cause and files a bug report). This type of thing gets very frustrating.
As you noticed, the VRA Tools use the Bridge JavaScript environment which I understand and find easy to use. Unfortunately, it has some limitations when creating a UI. The new CEP environment would much better, but I don't think I will be committing time to learn that given how few people use the VRA Tools.

If there is interest in the VRA Tools, I will continue to support them - at least keep them working, but I don't plan on adding new features. I should put it on GitHub in case someone else wants to develop it further.

I will support the VRA json script for Custom Panels, but I have know formal connection to the Custom Panels project itself. I hope it continues and adds new features.

**Comment by mrtngrsbch** [comment]
Hi @MetadataDeluxe,

I too have found Adobe Bridge to be very unstable as a platform, and for that reason I have been collaborating with [jExifToolGUI](https://github.com/hvdwolf/jExifToolGUI/) since last year to extend metadata editing to other namespaces, currently already editing ISAD(G) data. Throughout the year I hope to move forward with DC, VRA and others.

Thank you very much for your kind explanation. It is very similar to what I had imagined. Your roadmap is very similar to what I had in mind and I will take the lesson you offer.
Like you, I am also uneasy about how many people will actually use these tools and not use scarce time on topics that no one will see. 

Personally I think that jExifToolGUI (Java & Open Source) is more sustainable than Adobe Bridge. 

Please, if you are so kind, I would like to have your opinion about it, if you have one.

**Comment by MetadataDeluxe** [comment]
Hi @mrtngrsbch,

I have looked at [jExifToolGUI](https://github.com/hvdwolf/jExifToolGUI/) and found that it needs some improvements. I wish it had a thumbnail grid view rather than a single vertical row. Also, it seems to be very slow to load thumbnails. The user defined metadata tag combinations is a very good feature and is easy to set up, but once it is created, it doesn't have a good UI to edit metadata. 
There are other things that are a problem for artwork metadata.  For instance, the Keywords input on the Edit > XMP screen. If I enter a name containing a comma, it assumes the comma is a separator and two keywords are created.

Pettoruti, Emilio 
```
<dc:subject>
	<rdf:Bag>
	   <rdf:li>Pettoruti</rdf:li>
	   <rdf:li>Emilio</rdf:li>
	</rdf:Bag>
 </dc:subject>
```

If I use quotes around the name (as I do in Bridge), the value is wrong.

"Pettoruti, Emilio"
```
 <dc:subject>
	<rdf:Bag>
	   <rdf:li>Pettoruti -xmp:Subject=Emilio</rdf:li>
	</rdf:Bag>
 </dc:subject>
```
Exiftool is the best thing for reading and writing metadata, but most users need an easy to use GUI. jExifToolGUI has a lot of potential, but it needs some improvement to the UI and the functions. An open source project might be more sustainable - the developers of jExifToolGUI certainly are more responsive than Adobe. I am not an expert programmer so I can't say which coding environment will be the most sustainable. I created a small metadata app using Node.js (HTML5 & JavaScript) but became overwhelmed by the complexity of creating a stand-alone app.

I get frustrated with Bridge, but I have not found a better app for making custom panels with custom schemas. I keep looking though. I will play with jExifToolGUI some more.

**Comment by mrtngrsbch** [comment]
Hi @MetadataDeluxe,

Thank you very much for your feedback and bug report !
Indeed, we still have many issues to work on and your opinion is true and very valuable.
In the next days I will create new issues in this direction.

I am hopeful that in this year we will improve these drawbacks and many more things, such as improvements in the CSV-XML import/export. As you can imagine, all this work is done in spare time.

Thanks again and feel free to leave your questions, doubts or issues in the repository. [https://github.com/hvdwolf/jExifToolGUI]

**Comment by MetadataDeluxe** [comment]
Hello @mrtngrsbch,

I just completed an ExifTool config file for VRA Core https://github.com/MetadataDeluxe/VRA-Core-Essentials-ExifTool-config
Do you think this would be useful for [jExifToolGUI](https://github.com/hvdwolf/jExifToolGUI/)?

**Comment by mrtngrsbch** [comment]
OMG !
I still don't believe my eyes
I am eager to test VRA in ExifTool + jExifToolGUI

Let me try it out and confirm. At first sight it looks excellent.

I see you finally liked the idea of ExifTool ;-)

best

**Comment by MetadataDeluxe** [comment]
Once I looked closely at the ExifTool config example, it wasn't so hard to implement. Writing VRA with ExifTool was much more difficult than reading, but I figured it out. I tested all the tags to be sure they create the same XMP as my Bridge tools.

**Comment by mrtngrsbch** [comment]
Hi @MetadataDeluxe,

I have created the 'preset vrae' and everything works fine, except that I still can't copy the metadata from the image, to edit it.

![jExifToolGUI-vrae_view](https://user-images.githubusercontent.com/693328/115971525-55623200-a51f-11eb-9404-104262c98989.jpg)
![jExifToolGUI-vrae_Preset](https://user-images.githubusercontent.com/693328/115971528-58f5b900-a51f-11eb-8f02-c7785d6656ad.jpg)
